//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSAPI1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Department_Details
    {
        public int User_Id { get; set; }
       
        public string User_Name { get; set; }
        
        public string User_Password { get; set; }      
        public string Department_Name { get; set; }
    }
}
