//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSAPI1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade_Details
    {
        public int Grade_Id { get; set; }
        public string Grade { get; set; }
        public Nullable<int> Min_Salary { get; set; }
        public Nullable<int> Max_Salary { get; set; }
        public string Description { get; set; }
    }
}
